-- 精神科購物管理：登入、病房權限與操作紀錄
-- 請先備份 shared_sessions，再於 Supabase SQL Editor 執行本檔。

create table if not exists public.shared_sessions (
  ward_id text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.staff_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  card_number text not null unique,
  display_name text not null,
  role text not null default 'staff' check (role in ('staff', 'admin')),
  ward_id text not null,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  ward_id text not null,
  user_id uuid not null references auth.users(id),
  action text not null,
  patient_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists audit_logs_ward_created_idx
  on public.audit_logs (ward_id, created_at desc);

create or replace function public.has_ward_access(target_ward text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.staff_profiles
    where user_id = auth.uid() and ward_id = target_ward and active = true
  );
$$;

create or replace function public.is_ward_admin(target_ward text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.staff_profiles
    where user_id = auth.uid() and ward_id = target_ward
      and role = 'admin' and active = true
  );
$$;

grant execute on function public.has_ward_access(text) to authenticated;
grant execute on function public.is_ward_admin(text) to authenticated;

alter table public.shared_sessions enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.audit_logs enable row level security;

-- 移除舊版匿名讀寫權限。
drop policy if exists "anon can read shared sessions" on public.shared_sessions;
drop policy if exists "anon can insert shared sessions" on public.shared_sessions;
drop policy if exists "anon can update shared sessions" on public.shared_sessions;

drop policy if exists "ward members can read shared sessions" on public.shared_sessions;
create policy "ward members can read shared sessions"
on public.shared_sessions for select to authenticated
using (public.has_ward_access(ward_id));

drop policy if exists "ward members can insert shared sessions" on public.shared_sessions;
create policy "ward members can insert shared sessions"
on public.shared_sessions for insert to authenticated
with check (public.has_ward_access(ward_id));

drop policy if exists "ward members can update shared sessions" on public.shared_sessions;
create policy "ward members can update shared sessions"
on public.shared_sessions for update to authenticated
using (public.has_ward_access(ward_id))
with check (public.has_ward_access(ward_id));

drop policy if exists "users can read own profile" on public.staff_profiles;
create policy "users can read own profile"
on public.staff_profiles for select to authenticated
using (user_id = auth.uid() or public.is_ward_admin(ward_id));

drop policy if exists "admins can manage staff profiles" on public.staff_profiles;
create policy "admins can manage staff profiles"
on public.staff_profiles for all to authenticated
using (public.is_ward_admin(ward_id))
with check (public.is_ward_admin(ward_id));

drop policy if exists "members can add own audit logs" on public.audit_logs;
create policy "members can add own audit logs"
on public.audit_logs for insert to authenticated
with check (user_id = auth.uid() and public.has_ward_access(ward_id));

drop policy if exists "admins can read audit logs" on public.audit_logs;
create policy "admins can read audit logs"
on public.audit_logs for select to authenticated
using (public.is_ward_admin(ward_id));

notify pgrst, 'reload schema';

-- 建立帳號方式：
-- 1. 到 Authentication > Users 建立使用者，Email 格式為：卡號@psych-ward-a.local
-- 2. 取消寄送邀請，直接設定至少 8 碼臨時密碼。
-- 3. 將下列範例改成實際卡號、姓名與角色後執行，每位使用者一列：
-- insert into public.staff_profiles (user_id, card_number, display_name, role, ward_id)
-- select id, '123456', '王護理師', 'admin', 'psych-ward-a'
-- from auth.users where email = '123456@psych-ward-a.local';
